### ISSUE TITLE
Release stable v1.11.0 and beta v0.104.0

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#10487]
Like open-telemetry/opentelemetry-collector#9601, but for v0.104.0

**Performed by collector release manager**

- [x] Prepare stable core release v1.11.0
- [x] Tag and release stable core v1.11.0
- [x] Prepare beta core release v0.104.0
- [x] Tag and release beta core v0.104.0
- [x] Prepare contrib release v0.104.0
- [x] Tag and release contrib v0.104.0
- [x] Prepare otelcol-releases v0.104.0
- [x] open-telemetry/opentelemetry-collector#10499
- [x] open-telemetry/opentelemetry-collector#10500

**Performed by operator maintainers**

- [x] open-telemetry/opentelemetry-operator#3091

**Performed by helm chart maintainers**

- [x] open-telemetry/opentelemetry-helm-charts#1243

**Comment by codeboten** [comment]
This is complete
