### ISSUE TITLE
Improve scrapers/mdatagen tool to produce more user-friendly code and support user settings

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#10904]
# Metrics Builder for Scraper Receivers

Design document: https://docs.google.com/document/d/1OwDbIFlugS1rR0STv7rYBYcUjDZQ45pyVUvOSFfaRp4

### Provide a user-friendly interface for metrics reporting by mdatagen tool

Currently mdatagen tool produces `generated_metrics.go` files that contain mostly definitions of the metrics taken from `metadata.yaml` files. Scraper authors have to add some amount of repetitive code to each of the scrapers to fill the metrics with data points and send them downstream. We want to reduce the amount of the repetitive code and provide scraper authors with a simple interface for reporting metrics that will be generated from metadata.yaml files.

### Ability to change the default metrics representation by applying user settings

We need a way to customize the default representation of the metrics generated by mdatagen based on user's config. Once we move metrics generation to the Metrics Builder generated by mdatagen, it'll be be possible to customize metrics based on user settings.

As the first step, we want to provide a way to enable or disable any metrics based on user config. This functionality should be encapsulated in the Metrics Builder generated by mdatagen, so scraper authors don't need to deal with user settings. This will also provide a way to introduce  _optional_ metrics which are disabled by default just by changing `metadata.yaml` properties. 

### Metrics builder functionality:

- [x] Ability to disable particular metrics.
- [ ] open-telemetry/opentelemetry-collector#10726
- [ ] open-telemetry/opentelemetry-collector#10903
- [ ] open-telemetry/opentelemetry-collector#10074

### Migrated scrapers:

- [x] open-telemetry/opentelemetry-collector-contrib#7135
- [x] receiver/hostmetricsreceiver/internal/scraper/cpuscraper
- [x] receiver/hostmetricsreceiver/internal/scraper/diskscraper
- [x] open-telemetry/opentelemetry-collector-contrib#7136
- [x] open-telemetry/opentelemetry-collector-contrib#7137
- [x] open-telemetry/opentelemetry-collector-contrib#7138
- [x] receiver/hostmetricsreceiver/internal/scraper/networkscraper
- [x] open-telemetry/opentelemetry-collector-contrib#7139
- [x] open-telemetry/opentelemetry-collector-contrib#7140
- [x] open-telemetry/opentelemetry-collector-contrib#7141
- [x] open-telemetry/opentelemetry-collector-contrib#7142
- [x] open-telemetry/opentelemetry-collector-contrib#7143
- [x] open-telemetry/opentelemetry-collector-contrib#7144
- [x] open-telemetry/opentelemetry-collector-contrib#7145
- [x] open-telemetry/opentelemetry-collector-contrib#7146
- [x] open-telemetry/opentelemetry-collector-contrib#7147
- [x] open-telemetry/opentelemetry-collector-contrib#7148
- [x] receiver/redisreceiver
- [x] receiver/zookeeperreceiver

### Additional improvements

- [x] open-telemetry/opentelemetry-collector-contrib#8127
- [x] open-telemetry/opentelemetry-collector-contrib#9595
- [x] open-telemetry/opentelemetry-collector-contrib#8358
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7301
- [x] open-telemetry/opentelemetry-collector-contrib#8842
- [x] open-telemetry/opentelemetry-collector-contrib#15995
- [x] open-telemetry/opentelemetry-collector-contrib#16375
- [x] open-telemetry/opentelemetry-collector-contrib#18063
- [x] open-telemetry/opentelemetry-collector-contrib#16419
- [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18272

**Comment by codeboten** [comment]
transferred issue as mdatagen lives in the core repo now
