### ISSUE TITLE
[Tracking Issue][Document/Agree on] all packages/modules that will be marked as stable during second stability phase. 

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2676]
Phase 2 [more things MAY be added]:
- [ ] - client
- [ ] - config/configcheck
- [ ] - config/configerror
- [ ] - config/configrpc
- [ ] - config/confighttp
- [ ] - config/confignet
- [ ] - config/configtelemetry
- [ ] - config/configtest
- [ ] - config/configtls
- [ ] - obsreport 
- [ ] - obsreport/obsreporttest
- [ ] - service
- [ ] - service/defaultcomponents
- [ ] - translator/
- [ ] - exporter (at least config should be reviewed and stabilize)
  - [ ] exporterhelper
  - [ ] otlp/grpc
  - [ ] otlp/http
  - [ ] jaeger/grpc
  - [ ] zipkin
- [ ] processor (at least config should be reviewed and stabilize)
  - [ ] processorhelper
  - [ ] memorylimiter
  - [ ] batch
  - [ ] attributes/span/logs/metrics - see #3185
- [ ] extension (at least config should be reviewed and stabilize)
  - [ ] extensionhelper
  - [ ] pprof
  - [ ] zpages
  - [ ] health
- [ ] receiver (at least config should be reviewed and stabilize)
  - [ ] receiverhelper
  - [ ] oltp (grpc/http)
  - [ ] Jaeger
  - [ ] Zipkin

INVESTIGATE:

- config/configauth -  We have an issue to refactor this https://github.com/open-telemetry/opentelemetry-collector/issues/2603 and it is not clear if it will be ready for Phase 2.

EXCLUDED:

- consumer/simple. Not enough known usage to stabilize.

**Comment by alolita** [comment]
Superceded by issue #3474 - closing this one.
