### ISSUE TITLE
[Tracking issue] for all the packages that needs to be stabilized during Phase 1

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2677]
Tracking progress (mark done) when packages are ready for stability:

- [x] - component (only traces) - #3049
- [x] - component/componenterror
- [x] - component/componenthelper
- [x] - component/componenttest
- [x] - config - #3051
- [x] - consumer (only traces) - #3050
- [x] - consumer/consumererror
- [x] - consumer/consumerhelper
- [x] - consumer/consumertest
- [x] - consumer/pdata (only traces) - #2488

**Comment by alolita** [comment]
Can we update status on this issue?

**Comment by bogdandrutu** [comment]
@alolita status updated
