### ISSUE TITLE
Propagate auth data to downstream services

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#2734]
Based on the discussion around #2603, we agreed to attempt to propagate auth data to downstream services when a "passthrough'' option is defined in the auth configuration.

Status of this feature:

- [x] the server authenticators are adding the incoming auth information to the context
- [x] other components in the pipeline, starting with the receiver, have access to this information via the client package: https://github.com/open-telemetry/opentelemetry-collector/blob/a8ad0070de8d5de1cd5008d85dd5e33a06ff77dc/client/client.go#L142-L150
- [x] the PR open-telemetry/opentelemetry-collector-contrib#9241 will add the ability to add auth info to the telemetry data point itself
- [x] at this moment, there's no way to consume the auth information in the HTTP clients built from confighttp, so that we cannot just propagate a header from the server authenticator to a HTTP header
- [x] client authenticators should also be able to consume this data. For instance, the bearer token client authenticator could have a "source" attribute -- when it has a "passthrough" value, it could just reuse the bearer token seen by the server authenticator (probably the oidc server authenticator) (#4814)
- [x] batch by auth context so that batch processor preserves auth information and the context (#4544)

I believe this issue here is about the fourth point from the list above, so, it shouldn't be closed yet. I would expect the confighttp to be able to be configured with values coming from the context, in a similar way to what the attributes processor has (`from_context` option).

**Comment by jpkrohling** [comment]
This needs #2733.

**Comment by pavankrish123** [comment]
@jpkrohling. I am not sure if this fits into the story but we need exporters (at least the one using config gRPC and config http clients) to support multiple ways of authentication. 

- token based approach, where a static  token is slapped into Authorization headers while making a request. There is support for this approach already in our collector for both gRPC and HTTP clients. 

- client credentials approach (OAuth2 client) , where client credentials are taken as config and the token is derived and auto refreshed.  Pending #2603 has  the code for http clients but we need it for gRPC

- mTLS way 


Kindly advice if this is the right area whether these requirements need to be handled if not happy to open another item.

**Comment by jpkrohling** [comment]
@tigrannajaryan mentioned that we need a "passthrough" mode, where we propagate a specific header from the receiver to the exporter. This would require #2733.

**Comment by pavankrish123** [comment]
Thanks @jpkrohling

**Comment by jpkrohling** [comment]
I believe this is now complete.

**Comment by tigrannajaryan** [comment]
> I believe this is now complete.

@jpkrohling can you clarify how this works? If I want to passthrough a certain HTTP header how do I configure my OTLP receiver and OTLP exporter? I want to just make sure a specific header is preserved when it is received by the Collector and that header is present in the outgoing data. Is it possible to do?

**Comment by bputt-e** [comment]
@tigrannajaryan I believe once https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9241 is resolved, the auth info will be accessible

**Comment by tigrannajaryan** [comment]
So, I guess it means this is not yet complete. I will re-open the issue (@jpkrohling feel free to close if it is actually complete, but please add a comment that explain how it is done).

**Comment by jpkrohling** [comment]
Sorry, this has slipped from my radar. I'll work on documenting this next week

**Comment by atoulme** [comment]
Point 4 of your checklist links to a closed issue, can we mark this point as checked?
Is point 3 still current:
> at this moment, there's no way to consume the auth information in the HTTP clients built from confighttp, so that we cannot just propagate a header from the server authenticator to a HTTP header

I am under the impression that http headers are now available in context. Please let me know if I'm missing something.

**Comment by jpkrohling** [comment]
I believe the last items here are complete with both the work on batching by context keys and with header setter. Closing.
