### ISSUE TITLE
Auth-related tasks

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#3629]
This is a tracker for the auth-related tasks that should be done for GA, or soon after.

- [x] #3552, which specifies what should be included in the context. This is required for GA, because server authenticators need to know what to publish as part of the context.
- [ ] #2733, which specifies how data is placed in the pdata from the context. This is not required for GA, but it's a nice to have, as it would potentially uncover API changes needed by the general auth feature.
- [ ] #2734, which covers a "passthrough" authenticator, sending the same auth data it received to a backing service. This can be done post-GA.

**Comment by tigrannajaryan** [comment]
Should #3552 be replaced by #3745?

**Comment by jpkrohling** [comment]
Yes

**Comment by tigrannajaryan** [comment]
@bogdandrutu @jpkrohling shouldn't this be labeled `required-for-ga`? I am worried that it may require breaking changes and won't be possible to do after GA.

**Comment by jpkrohling** [comment]
I have to agree: right now, given that we haven't made progress with #3745, I would be a bit concerned about having a GA without understanding what needs to be changed to accommodate that PR.

@bogdandrutu, when you have some time, can we do a pair programming session and get that sorted out?
