### ISSUE TITLE
Release v0.49.0

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#5204]
- [x] open-telemetry/opentelemetry-collector#5205
- [x] open-telemetry/opentelemetry-collector#5206
- [x] open-telemetry/opentelemetry-collector-contrib#9263
- [x] open-telemetry/opentelemetry-collector-contrib#9264
- [x] open-telemetry/opentelemetry-collector-releases#99
- [x] open-telemetry/opentelemetry-collector-releases#100
- [x] open-telemetry/opentelemetry-operator#819
