### ISSUE TITLE
Provide examples on how to create components

### ISSUE THREAD

**Issue by hickeyma** [open-telemetry/opentelemetry-collector#5675]
**EDIT: I have kept all original text (with strikethrough) but have made modifications based on feedback**

It would be very helpful and improve usability if an example~~s~~ ~~were~~ was provided for ~~the different~~ a component~~s like receivers, processor, exporters and extensions~~. This would simplify the process of creating a component for new users.

~~Examples could be added to the Go documentation for the component package. Refer to [Testable Examples in Go](https://go.dev/blog/examples) for more details.~~

This request follows a discussion with @mx-psi.

### Tasks

- [x] Add  [Building a Trace Receiver](https://opentelemetry.io/docs/collector/trace-receiver/) reference to collector contrib [Adding New Components](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components) section (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12490)
- [x] Add  [Building a Trace Receiver](https://opentelemetry.io/docs/collector/trace-receiver/) reference to collector [When adding a new component](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component) section (#5690)
- [x] Add "Building Component" sub menu to [Collector Docs](https://opentelemetry.io/docs/collector/) which would contain [Building a custom authenticator](https://opentelemetry.io/docs/collector/custom-auth/) and [Building a Trace Receiver](https://opentelemetry.io/docs/collector/trace-receiver/)
- [ ] [Testable Examples in Go](https://go.dev/blog/examples) which may not be end-to-end and uses some dummy implementation (so e.g. a receiver that generates a gauge point every minute? or some sort of simple logging exporter?),  that still showcases how to use the interface (Refer to https://github.com/open-telemetry/opentelemetry-collector/issues/5675#issuecomment-1206557809)

**Modules where we would want to have testable examples**:

**Comment by mx-psi** [comment]
Should we create an checklist for each kind of component (receiver, processor, exporter, extension...)? So that this can potentially be taken on by several people

**Comment by fatsheep9146** [comment]
I agree, I think we can also learn from go-contrib new instrumentation library request [template](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/new/choose) to define following steps/tasks to build a usable component.

## Tasks

- Code complete:
  - [ ] Comprehensive unit tests.
  - [ ] End-to-end integration tests.
  - [ ] Tests all passing.
  - [ ] Instrumentation functionality verified.
- Documented
  - [ ] Added to the [OpenTelemetry Registry](https://opentelemetry.io/registry/)
  - [ ] README included for the module describing high-level purpose.
  - [ ] Complete documentation of all public API including package documentation.
  - [ ] [Instrumentation documentation](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/README.md#instrumentation-packages) updated.
- Examples
  - [ ] `Dockerfile` file to build example application.
  - [ ] `docker-compose.yml` to run example in a docker environment to demonstrate instrumentation.

**Comment by hickeyma** [comment]
Good idea @mx-psi @fatsheep9146. I'll add to the description when I get a chance.

**Comment by mx-psi** [comment]
> Is this about adding documentation for people creating new components (ie, writing Go code that ends up in a distribution), or is it for end-users, configuring components available in a collector distribution?

The former: writing Go code

**Comment by fatsheep9146** [comment]
> Good ideas @mx-psi @fatsheep9146. I'll add to the description when I get a chance.

@hickeyma  Excellent :-),  I’d love to help with review or contribute for this issue if you need.

**Comment by hickeyma** [comment]
Following the feedback from @jpkrohling in https://github.com/open-telemetry/opentelemetry-collector/issues/5675#issuecomment-1181985956, I investigated this further. Here is the feedback from my investigation:

- The [Building a Trace Receiver](https://opentelemetry.io/docs/collector/trace-receiver/) doc is an excellent reference for building a component and I think it trancends a trace receiver component. I therefore think that having examples per component type would be overhead.
- [Examples](https://go.dev/blog/examples) added to the Go documentation is very nice capability but I'm not sure the component models fits nicely with it because the [Building a Trace Receiver](https://opentelemetry.io/docs/collector/trace-receiver/) doc shows how involved building a component is and not just short snappy end to end code. It also requires a lot of background explanation to make decisions.
- By adding links in key existing documentation would direct a user to useful documentation like the [Building a Trace Receiver](https://opentelemetry.io/docs/collector/trace-receiver/) doc.

I have updated the description to breakdown what I propose the tasks could be for this work. 

@mx-psi @fatsheep9146 @jpkrohling Please let me know what you think.

**Comment by mx-psi** [comment]
@hickeyma I think having a link to that doc is definitely better than not having anything! The benefit of having a testable example is that we ensure that the examples will always be kept up to date (since CI will fail otherwise), but it's true that they won't be end to end examples

**Comment by hickeyma** [comment]
@mx-psi Ok, thanks for the feedback. 

> I think having a link to that doc is definitely better than not having anything!

I have pushed #5690 and https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12490 to see provide context and references.

> The benefit of having a testable example is that we ensure that the examples will always be kept up to date (since CI will fail otherwise), but it's true that they won't be end to end examples

I agree that this would be beneficial. Does this work when its not an end to end example for a user?

**Comment by mx-psi** [comment]
I took a look at your PRs @hickeyma, they make sense to me :)

> Does this work when its not an end to end example for a user?

I don't understand what you mean in this question, sorry

**Comment by hickeyma** [comment]
> I don't understand what you mean in this question, sorry

I am wondering if providing a testable example which is not end to end would make sense for the components?

**Comment by hickeyma** [comment]
> I’d love to help with review or contribute for this issue if you need.

@fatsheep9146 Let me know if you would like to tackle the open issue of sub menu to collector docs (refer to item in description).

**Comment by mx-psi** [comment]
> I am wondering if providing a testable example which is not end to end would make sense for the components?

Ah, okay, thanks for clarifying! I think there is some value (maybe not only for component developers but also for other users of the Go API) and we can have some dummy implementation (so e.g. a receiver that generates a gauge point every minute? or some sort of simple logging exporter?) that still showcases how to use the interface.

Do you agree?

**Comment by Chinwendu20** [comment]
The third in the checklist should be modified in the opentelemetry.io repo right?

**Comment by hickeyma** [comment]
@Chinwendu20 It should be. Are you interested in pushing a PR?

**Comment by Enzujp** [comment]
Hello @hickeyma , if it is still valid, I'd like to work on the third item in the checklist!

**Comment by hickeyma** [comment]
@Enzujp Haven't looked at it in over a year. Maybe check the docs and see?

**Comment by Enzujp** [comment]
Will do just that.

**Comment by heitorganzeli** [comment]
looks like all docs were updated. maybe this issue should be closed

**Comment by mx-psi** [comment]
@heitorganzeli We would still benefit from testable examples IMO, if you are looking to contribute I am happy to help explain how to do this

**Comment by heitorganzeli** [comment]
hi @mx-psi , I can work on some examples. If you have more info on where and how to do them it would be helpful

**Comment by mx-psi** [comment]
@heitorganzeli just to get started, this is only tangentially related to building a component but you could add a testable example to https://github.com/open-telemetry/opentelemetry-collector/blob/main/confmap/xconfmap/ that looks similar to https://opentelemetry.io/docs/collector/building/receiver/#designing-and-validating-receiver-settings by leveraging the 'larger examples' explanation here https://go.dev/blog/examples#larger-examples

Once you have that ready, feel free to ping me and I can review, and then we can think about the examples for e.g. receiver

**Comment by heitorganzeli** [comment]
created a PR with a simple usage example. not sure if you meant something more complex. 

but, might be too much to really build a full receiver on the example code

**Comment by heitorganzeli** [comment]
hello @mx-psi 

do you have a list of packages for me to work on next? 

also, not sure why my PR https://github.com/open-telemetry/opentelemetry-collector/pull/12832 is getting blocked...

**Comment by heitorganzeli** [comment]
great, i'll start with the receiver then, since i had that previous example done

**Comment by heitorganzeli** [comment]
I've just published the PR: https://github.com/open-telemetry/opentelemetry-collector/pull/12922

Please take a look when you have time

**Comment by heitorganzeli** [comment]
I've just published another PR with exporter testable example: https://github.com/open-telemetry/opentelemetry-collector/pull/12922

Please take a look when you have time

**Comment by parv18050212** [comment]
Hi! I’d love to work on this issue as my first open-source contribution. Let me know if it's still available.

**Comment by mx-psi** [comment]
@parv18050212 I added some subissues, I would suggest picking just one of them to get started. I think #13144 could be a good start

**Comment by parv18050212** [comment]
sure i will will work on #13144

**Comment by wedge22** [comment]
I am new to Go and read this was a good first issue to work on, is work still required, if so can you confirm what is required.

**Comment by shantanu-1607** [comment]
hi @hickeyma , i would love to work on this issue, can i be assigned this?

**Comment by mx-psi** [comment]
I am going to close this issue as completed since I believe all steps on the original list are done
