### ISSUE TITLE
Release v0.56.0

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#5714]
- [x] open-telemetry/opentelemetry-collector#5716
- [x] open-telemetry/opentelemetry-collector#5715
- [x] open-telemetry/opentelemetry-collector-contrib#12616
- [x] open-telemetry/opentelemetry-collector-contrib#12617
- [x] open-telemetry/opentelemetry-collector-releases#168
- [x] open-telemetry/opentelemetry-collector-releases#166
- [x] open-telemetry/opentelemetry-operator#996
- [x] open-telemetry/opentelemetry-helm-charts#282
