### ISSUE TITLE
Release v0.58.0

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#5884]
**Performed by collector release manager**

- [x] open-telemetry/opentelemetry-collector#5885
- [x] open-telemetry/opentelemetry-collector#5886
- [x] open-telemetry/opentelemetry-collector#5887
- [x] open-telemetry/opentelemetry-collector#5888
- [x] open-telemetry/opentelemetry-collector#5889
- [x] open-telemetry/opentelemetry-collector#5890

**Performed by operator maintainers**

- [x] open-telemetry/opentelemetry-operator#1035

**Performed by helm chart maintainers**

- [x] open-telemetry/opentelemetry-helm-charts#319

**Comment by yuriolisa** [comment]
I think this issue can be closed.
