### ISSUE TITLE
Split components into their own modules

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#5992]
Depends on open-telemetry/opentelemetry-collector#5991.

On August 10, during the SIG meeting, we agreed on splitting components into modules, such as the OTLP Exporter and Receiver. This should be done after the changes that would be part of open-telemetry/opentelemetry-collector#5991, so we can take advantage of the tooling.

List of modules, from @bogdandrutu's comment:

- [x] open-telemetry/opentelemetry-collector#6184
- [x] #6526
- [x] open-telemetry/opentelemetry-collector#6185
- [x] open-telemetry/opentelemetry-collector#6186
- [x] open-telemetry/opentelemetry-collector#6187
- [x] open-telemetry/opentelemetry-collector#6188
- [x] open-telemetry/opentelemetry-collector#6189
- [x] open-telemetry/opentelemetry-collector#6190
- [x] open-telemetry/opentelemetry-collector#6191
- [x] open-telemetry/opentelemetry-collector#5564
- [x] open-telemetry/opentelemetry-go-build-tools#146

## Migration instructions
As part of splitting these components into their own packages,  users of these components will need to modify their Collector builder configuration to use `gomod` directly, the following:

```
exporters:
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector v0.63.0
```
will become:
```
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.63.0
```

**Comment by bogdandrutu** [comment]
Here is a first take on this:

* `pdata`
* `confmap`
* `consumer`, I think current `client` should be merged into the `consumer`. Since the `client` information (the info that we add about connection/request) is consumed by the Consumers (Processor/Exporter are all consumers).
* `component`. One question is if we want to have this package OR move everything into `go.opentelemetry.io/collector/CMP` (where CMP is one of receiver/processor/exporter/extension).
* `processor/*` in each individual package. The `processorhelper` may be embedded into `component` maybe? Otherwise maybe a better name?
* `exporter/*` in each individual package. Not sure yet what to do with `exporterhelper`
* `receiver/*` in each individual package. The current "scraper` related packages I would move them into a `scraper/` top directory and package.
* `extension/*` in each individual package.
* For service I would do https://github.com/open-telemetry/opentelemetry-collector/issues/5564

I think these are enough things to think about, and start working on.

**Comment by jpkrohling** [comment]
Thanks for this list! I'll start working on this once we have a go.work for this repo.

**Comment by jpkrohling** [comment]
Now that we have a decision about go work, I'll start the split of this into their own modules.

**Comment by codeboten** [comment]
One question that comes to mind when looking at this list, are we planning on releasing these packages independently in the future? If so we'll need to figure out what that looks like as well.

It would be great to only release packages with changed code.

**Comment by bryan-aguilar** [comment]
I can take the action item to add `crosslink` support to this repository in the same way that it is implemented in contrib. Should be a quick™ and can make inserting those replace statements a bit easier.
