### ISSUE TITLE
Release v0.60.0

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#6067]
Like open-telemetry/opentelemetry-collector#4522, but for v0.60.0

**Performed by collector release manager**

- [x] open-telemetry/opentelemetry-collector#6069
- [x] open-telemetry/opentelemetry-collector#6070
- [x] open-telemetry/opentelemetry-collector#6071
- [x] open-telemetry/opentelemetry-collector#6072
- [x] open-telemetry/opentelemetry-collector#6073
- [x] open-telemetry/opentelemetry-collector#6074

**Performed by operator maintainers**

- [x] open-telemetry/opentelemetry-operator#1099

**Performed by helm chart maintainers**

- [x] open-telemetry/opentelemetry-helm-charts#362
