### ISSUE TITLE
Release v0.64.0

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#6495]
Like open-telemetry/opentelemetry-collector#4522, but for v0.64.0

**Performed by collector release manager**

- [x] open-telemetry/opentelemetry-collector#6496
- [x] open-telemetry/opentelemetry-collector#6497
- [x] open-telemetry/opentelemetry-collector#6498
- [x] open-telemetry/opentelemetry-collector#6499
- [x] open-telemetry/opentelemetry-collector#6500
- [x] open-telemetry/opentelemetry-collector#6501

**Performed by operator maintainers**

- [ ] open-telemetry/opentelemetry-operator#1241

**Performed by helm chart maintainers**

- [x] open-telemetry/opentelemetry-helm-charts#494
