### ISSUE TITLE
Release v0.68.0

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#6818]
Like open-telemetry/opentelemetry-collector#4522, but for v0.68.0

**Performed by collector release manager**

- [x] open-telemetry/opentelemetry-collector#6819
- [x] Tag and release stable core v1.0.0-RC.2
- [x] open-telemetry/opentelemetry-collector#6821
- [x] Tag and release beta core v0.68.0
- [x] open-telemetry/opentelemetry-collector#6823
- [x] Tag and release contrib v0.68.0
- [x] open-telemetry/opentelemetry-collector#6824
- [x] open-telemetry/opentelemetry-collector#6842

**Performed by operator maintainers**

- [x] open-telemetry/opentelemetry-operator#1374

**Performed by helm chart maintainers**

- [x] open-telemetry/opentelemetry-collector#6848

**Comment by mx-psi** [comment]
Blocked by open-telemetry/opentelemetry-collector-contrib#17077

**Comment by mx-psi** [comment]
All steps have been completed
