### ISSUE TITLE
Release v0.70.0

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6995]
Like open-telemetry/opentelemetry-collector#4522, but for v1.0.0-RC4/v0.70.0

**Performed by collector release manager**

- [x] open-telemetry/opentelemetry-collector#6996
- [x] Tag and release stable core v1.0.0-RC3
- [x] open-telemetry/opentelemetry-collector#7000
- [x] Tag and release beta core v0.70.0
- [x] open-telemetry/opentelemetry-collector-contrib#17973
- [x] Tag and release contrib v0.70.0
- [x] open-telemetry/opentelemetry-collector-releases#273
- [x] Release binaries and container images v0.70.0

**Performed by operator maintainers**

- [ ] open-telemetry/opentelemetry-operator#1391

**Performed by helm chart maintainers**

- [x] open-telemetry/opentelemetry-helm-charts#613
